apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: quay.io/coreos/hyperkube:v1.3.5_coreos.0
    command:
    - /hyperkube
    - apiserver
    - --bind-address=0.0.0.0
    - --insecure-bind-address=0.0.0.0
    - --etcd-servers=http://$private_ipv4$:2379
    - --allow-privileged=true
    - --service-cluster-ip-range=10.0.2.0/24
    - --service-node-port-range=1-33000
    - --secure-port=443
    - --advertise-address=$private_ipv4$
    - --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
    - --tls-cert-file=/etc/kubernetes/ssl/server.pem
    - --tls-private-key-file=/etc/kubernetes/ssl/server-key.pem
    - --client-ca-file=/etc/kubernetes/ssl/ca.pem
    - --service-account-key-file=/etc/kubernetes/ssl/server-key.pem
    ports:
    - containerPort: 443
      name: https
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/kubernetes/cloud.conf
      name: cloud-conf-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
  - hostPath:
      path: /etc/kubernetes/cloud.conf
    name: cloud-conf-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
